# Generated by Django 6.0.2 on 2026-02-21 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_type', models.CharField(choices=[('properties', 'Properties'), ('units', 'Units'), ('tenants', 'Tenants')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(default=list, help_text='List of error messages with row numbers')),
                ('warnings', models.JSONField(default=list, help_text='List of warning messages with row numbers')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csv_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CSV Import Log',
                'verbose_name_plural': 'CSV Import Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SetupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('steps_completed', models.JSONField(default=dict, help_text='Dict of step_name -> {completed_at, skipped, warnings}')),
                ('setup_version', models.CharField(default='1.0.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Setup Configuration',
                'verbose_name_plural': 'Setup Configuration',
            },
        ),
    ]
