# Generated by Django 6.0.2 on 2026-02-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_lifecycle', '0002_tenantemergencycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of when to use this preset.')),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('student', 'Student Housing'), ('senior', 'Senior Living'), ('commercial', 'Commercial'), ('subsidized', 'Subsidized/Section 8'), ('custom', 'Custom')], default='residential', max_length=20)),
                ('icon', models.CharField(default='bi-house', help_text='Bootstrap icon class for display.', max_length=50)),
                ('is_system', models.BooleanField(default=False, help_text='System presets cannot be deleted.')),
                ('is_active', models.BooleanField(default=True)),
                ('steps_config', models.JSONField(default=dict, help_text='Configuration for each onboarding step.')),
                ('collect_vehicles', models.BooleanField(default=True)),
                ('collect_employment', models.BooleanField(default=True)),
                ('require_renters_insurance', models.BooleanField(default=False)),
                ('require_id_verification', models.BooleanField(default=False)),
                ('welcome_message', models.TextField(blank=True)),
                ('property_rules', models.TextField(blank=True)),
                ('move_in_checklist', models.JSONField(default=list)),
                ('invitation_email_subject', models.CharField(default='Welcome! Complete Your Move-In Process', max_length=200)),
                ('invitation_email_body', models.TextField(blank=True)),
                ('invitation_sms_body', models.CharField(blank=True, max_length=320)),
                ('link_expiry_days', models.PositiveSmallIntegerField(default=14)),
                ('default_fees', models.JSONField(default=list, help_text='List of default fee configurations.')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
