# Generated by Django 6.0.2 on 2026-02-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_lifecycle', '0005_additional_onboarding_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingsession',
            name='otp_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='onboardingsession',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
