# Generated by Django 6.0.2 on 2026-02-21 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_lease_auto_renewal_lease_fully_executed_at_and_more'),
        ('tenant_lifecycle', '0006_add_otp_fields_to_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingsession',
            name='collected_data',
            field=models.JSONField(blank=True, default=dict, help_text='Personal info collected during onboarding (DOB, ID info).'),
        ),
        migrations.AddField(
            model_name='tenantidverification',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_verifications', to='leases.lease'),
        ),
    ]
