# Generated by Django 6.0.2 on 2026-02-21 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_lease_auto_renewal_lease_fully_executed_at_and_more'),
        ('tenant_lifecycle', '0007_add_collected_data_and_lease_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingsession',
            name='lease',
            field=models.ForeignKey(help_text='Lease for this onboarding (required).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_sessions', to='leases.lease'),
        ),
    ]
