# Generated by Django 6.0.2 on 2026-02-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='drivers_license_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='drivers_license_state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='ssn_last_four',
            field=models.CharField(blank=True, default='', help_text='Last 4 digits of SSN for verification purposes.', max_length=4),
        ),
    ]
