# Generated by Django 5.2.11 on 2026-02-19 02:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='billing_mode',
            field=models.CharField(blank=True, default='', help_text='Billing mode at time of generation: fixed, variable, or empty for non-utility items.', max_length=10),
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(help_text='Description of what this token is used for.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UtilityConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utility_type', models.CharField(choices=[('water', 'Water'), ('electric', 'Electric'), ('gas', 'Gas'), ('trash', 'Trash'), ('parking', 'Parking'), ('pet_fee', 'Pet Fee')], max_length=15)),
                ('billing_mode', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable'), ('included', 'Included')], default='included', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, help_text="Current monthly rate. Ignored when billing_mode is 'included'.", max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_configs', to='properties.unit')),
            ],
            options={
                'ordering': ['unit', 'utility_type'],
                'unique_together': {('unit', 'utility_type')},
            },
        ),
        migrations.CreateModel(
            name='UtilityRateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_billing_mode', models.CharField(blank=True, default='', max_length=10)),
                ('new_billing_mode', models.CharField(blank=True, default='', max_length=10)),
                ('source', models.CharField(default='admin_gui', help_text='How the change was made: admin_gui, api, bulk_set', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_rate_changes', to=settings.AUTH_USER_MODEL)),
                ('utility_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_logs', to='billing.utilityconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
