# Generated by Django 5.2.11 on 2026-02-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoicelineitem_billing_mode_apitoken_utilityconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilityconfig',
            name='billing_mode',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable'), ('included', 'Included'), ('tenant_pays', 'Tenant Pays Separately')], default='included', max_length=15),
        ),
    ]
