# Generated by Django 5.2.11 on 2026-02-19 04:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_utilityconfig_billing_mode'),
        ('leases', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcycle',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='properties.property'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='late_fees_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='credit_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('online', 'Online Payment'), ('check', 'Check'), ('cash', 'Cash'), ('money_order', 'Money Order'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Prepayment Credit')], max_length=15),
        ),
        migrations.CreateModel(
            name='LateFeeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_type', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_date', models.DateField()),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_fee_logs', to='billing.invoice')),
                ('line_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='late_fee_log', to='billing.invoicelineitem')),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyBillingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_generate_invoices', models.BooleanField(default=True, help_text='Automatically generate monthly invoices for this property.')),
                ('default_due_day', models.PositiveSmallIntegerField(default=1, help_text='Day of the month rent is due (1-28).')),
                ('late_fee_enabled', models.BooleanField(default=False)),
                ('grace_period_days', models.PositiveSmallIntegerField(default=5, help_text='Days after due date before late fee applies.')),
                ('late_fee_type', models.CharField(choices=[('flat', 'Flat Amount'), ('percentage', 'Percentage of Balance')], default='flat', max_length=10)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, help_text='Flat dollar amount or percentage (e.g., 5 for 5%).', max_digits=10)),
                ('late_fee_frequency', models.CharField(choices=[('one_time', 'One Time'), ('recurring_monthly', 'Recurring Monthly')], default='one_time', max_length=20)),
                ('late_fee_cap', models.DecimalField(decimal_places=2, default=0, help_text='Maximum total late fees per invoice. 0 = no cap.', max_digits=10)),
                ('interest_enabled', models.BooleanField(default=False)),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual interest rate as percentage (e.g., 12.00 for 12%).', max_digits=5)),
                ('default_invoice_notes', models.TextField(blank=True, default='', help_text='Default notes appended to auto-generated invoices.')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_config', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Billing Configuration',
            },
        ),
        migrations.CreateModel(
            name='RecurringCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_type', models.CharField(choices=[('rent', 'Rent'), ('water', 'Water'), ('electric', 'Electric'), ('gas', 'Gas'), ('trash', 'Trash'), ('parking', 'Parking'), ('pet_fee', 'Pet Fee'), ('late_fee', 'Late Fee'), ('other', 'Other')], max_length=15)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('one_time', 'One Time')], default='monthly', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_charges', to='leases.lease')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_charges', to='properties.property')),
            ],
            options={
                'ordering': ['charge_type', 'description'],
            },
        ),
    ]
