# Generated by Django 5.2.11 on 2026-02-19 04:56

from decimal import Decimal

from django.db import migrations, models


def populate_billing_configs(apps, schema_editor):
    """Create a PropertyBillingConfig for each existing Property."""
    Property = apps.get_model("properties", "Property")
    PropertyBillingConfig = apps.get_model("billing", "PropertyBillingConfig")

    for prop in Property.objects.all():
        PropertyBillingConfig.objects.get_or_create(
            property=prop,
            defaults={
                "auto_generate_invoices": True,
                "default_due_day": 1,
                "late_fee_enabled": False,
                "grace_period_days": 5,
                "late_fee_type": "flat",
                "late_fee_amount": Decimal("0.00"),
                "late_fee_frequency": "one_time",
                "late_fee_cap": Decimal("0.00"),
                "interest_enabled": False,
                "annual_interest_rate": Decimal("0.00"),
            },
        )


def populate_recurring_charges(apps, schema_editor):
    """Create a rent RecurringCharge for each active Lease."""
    Lease = apps.get_model("leases", "Lease")
    RecurringCharge = apps.get_model("billing", "RecurringCharge")

    for lease in Lease.objects.filter(status="active"):
        RecurringCharge.objects.get_or_create(
            lease=lease,
            charge_type="rent",
            defaults={
                "description": f"Monthly Rent",
                "amount": lease.monthly_rent,
                "frequency": "monthly",
                "is_active": True,
                "start_date": lease.start_date,
                "end_date": lease.end_date,
            },
        )


def compute_late_fees_total(apps, schema_editor):
    """Backfill late_fees_total from existing late_fee line items."""
    Invoice = apps.get_model("billing", "Invoice")
    InvoiceLineItem = apps.get_model("billing", "InvoiceLineItem")

    for invoice in Invoice.objects.all():
        total = (
            InvoiceLineItem.objects.filter(invoice=invoice, charge_type="late_fee")
            .aggregate(t=models.Sum("amount"))
            .get("t")
        )
        if total and total > 0:
            invoice.late_fees_total = total
            invoice.save(update_fields=["late_fees_total"])


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_billingcycle_property_invoice_late_fees_total_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_billing_configs, migrations.RunPython.noop
        ),
        migrations.RunPython(
            populate_recurring_charges, migrations.RunPython.noop
        ),
        migrations.RunPython(
            compute_late_fees_total, migrations.RunPython.noop
        ),
    ]
