# Generated by Django 5.2.11 on 2026-02-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_populate_billing_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reward_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='charge_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('water', 'Water'), ('electric', 'Electric'), ('gas', 'Gas'), ('trash', 'Trash'), ('parking', 'Parking'), ('pet_fee', 'Pet Fee'), ('late_fee', 'Late Fee'), ('reward_discount', 'Reward Discount'), ('other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('online', 'Online Payment'), ('check', 'Check'), ('cash', 'Cash'), ('money_order', 'Money Order'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Prepayment Credit'), ('reward', 'Reward Applied')], max_length=15),
        ),
        migrations.AlterField(
            model_name='recurringcharge',
            name='charge_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('water', 'Water'), ('electric', 'Electric'), ('gas', 'Gas'), ('trash', 'Trash'), ('parking', 'Parking'), ('pet_fee', 'Pet Fee'), ('late_fee', 'Late Fee'), ('reward_discount', 'Reward Discount'), ('other', 'Other')], max_length=15),
        ),
    ]
