# Generated by Django 5.2.11 on 2026-02-19 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_payment_reward_applied_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinPriceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('btc_usd_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('source', models.CharField(default='coingecko', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('online', 'Online Payment'), ('check', 'Check'), ('cash', 'Cash'), ('money_order', 'Money Order'), ('bank_transfer', 'Bank Transfer'), ('ach', 'ACH Bank Transfer'), ('crypto', 'Cryptocurrency'), ('credit', 'Prepayment Credit'), ('reward', 'Reward Applied')], max_length=15),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('square', 'Square'), ('authorize_net', 'Authorize.Net'), ('braintree', 'Braintree'), ('plaid_ach', 'Plaid + ACH'), ('bitcoin', 'Bitcoin')], max_length=20),
        ),
        migrations.CreateModel(
            name='BitcoinPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('btc_address', models.CharField(db_index=True, max_length=100, unique=True)),
                ('derivation_index', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('mempool', 'In Mempool'), ('confirmed', 'Confirmed'), ('expired', 'Expired'), ('overpaid', 'Overpaid'), ('underpaid', 'Underpaid')], db_index=True, default='pending', max_length=15)),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('btc_usd_rate', models.DecimalField(decimal_places=2, help_text='BTC-USD rate at time of creation', max_digits=15)),
                ('expected_satoshis', models.PositiveBigIntegerField()),
                ('received_satoshis', models.PositiveBigIntegerField(default=0)),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('txid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='btc_payments', to='billing.invoice')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btc_detail', to='billing.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BitcoinWalletConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('xpub', models.CharField(help_text='Extended public key for watch-only address derivation', max_length=200)),
                ('derivation_path', models.CharField(default="m/84'/0'/0'", max_length=50)),
                ('next_index', models.PositiveIntegerField(default=0)),
                ('network', models.CharField(choices=[('bitcoin', 'Mainnet'), ('testnet', 'Testnet')], default='bitcoin', max_length=10)),
                ('payment_gateway_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btc_wallet_config', to='billing.paymentgatewayconfig')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=100)),
                ('event_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='billing.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
