# Generated by Django 6.0.2 on 2026-02-20 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_deleted_at_document_deleted_by_and_more'),
        ('leases', '0002_lease_auto_renewal_lease_fully_executed_at_and_more'),
        ('properties', '0002_property_manager_email_property_manager_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Markdown content (frozen copy from template or custom)')),
                ('rendered_html', models.TextField(blank=True, default='', help_text='Rendered HTML with variables substituted')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Signatures'), ('partial', 'Partially Signed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=15)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When sent to signers', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When all signatures collected', null=True)),
                ('final_pdf', models.FileField(blank=True, help_text='Generated PDF after completion', null=True, upload_to='edocuments/signed/%Y/%m/')),
                ('is_locked', models.BooleanField(default=False, help_text='Document is read-only after completion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('edoc_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edocuments', to='properties.property')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edocuments', to='leases.lease')),
                ('tenant', models.ForeignKey(blank=True, help_text='Primary tenant for this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edocuments_received', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'eDocument',
                'verbose_name_plural': 'eDocuments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EDocumentSigner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant'), ('tenant2', 'Tenant 2'), ('tenant3', 'Tenant 3'), ('tenant4', 'Tenant 4'), ('cosigner', 'Co-Signer')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('signature_image', models.TextField(blank=True, default='', help_text='Base64 encoded signature image')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='documents.edocument')),
                ('user', models.ForeignKey(blank=True, help_text='Linked user account for portal access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edocument_signers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'eDocument Signer',
                'verbose_name_plural': 'eDocument Signers',
                'ordering': ['role'],
                'unique_together': {('document', 'role')},
            },
        ),
        migrations.CreateModel(
            name='EDocumentSignatureBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_type', models.CharField(choices=[('signature', 'Signature'), ('initials', 'Initials')], max_length=10)),
                ('block_order', models.PositiveIntegerField(help_text='Order of appearance in document (parsed from markdown)')),
                ('image', models.TextField(blank=True, default='', help_text='Base64 encoded signature/initials image')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_blocks', to='documents.edocument')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='documents.edocumentsigner')),
            ],
            options={
                'verbose_name': 'eDocument Signature Block',
                'verbose_name_plural': 'eDocument Signature Blocks',
                'ordering': ['block_order'],
            },
        ),
        migrations.CreateModel(
            name='EDocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('lease', 'Lease Agreement'), ('pet_agreement', 'Pet Agreement'), ('termination', 'Lease Termination'), ('addendum', 'Lease Addendum'), ('notice', 'Notice'), ('disclosure', 'Disclosure'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('content', models.TextField(help_text='Markdown content with {{variables}} and [SIGNATURE:Role] tags')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, help_text='If set, template is only available for this property', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edocument_templates', to='properties.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'eDocument Template',
                'verbose_name_plural': 'eDocument Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='edocument',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Source template (if created from template)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.edocumenttemplate'),
        ),
    ]
