"""
Data migration to seed comprehensive eDocument templates for property management.

Based on industry-standard landlord documents including:
- Lease agreements and variations
- Addendums (pet, parking, smoking, etc.)
- Required disclosures (lead paint, mold, etc.)
- Notices (vacate, rent increase, entry)
- Checklists and receipts
- Welcome and communication letters
"""

from django.db import migrations


# =============================================================================
# LEASE AGREEMENTS
# =============================================================================

MONTH_TO_MONTH_AGREEMENT = """# MONTH-TO-MONTH RENTAL AGREEMENT

This Month-to-Month Rental Agreement ("Agreement") is entered into on {{current_date}} between:

**LANDLORD:** {{landlord_name}}
**TENANT(S):** {{tenant_name}}

---

## 1. PREMISES

The Landlord agrees to rent to the Tenant the property located at:

**Address:** {{property_address}}
**Unit:** {{unit_number}}

---

## 2. TERM

This is a month-to-month tenancy. The tenancy shall begin on {{lease_start_date}} and shall continue on a month-to-month basis until terminated by either party.

**Termination Notice:** Either party may terminate this Agreement by providing written notice at least **30 days** before the intended termination date. The termination date must be the last day of a rental period.

---

## 3. RENT

**Monthly Rent:** {{monthly_rent}}
**Due Date:** Rent is due on the {{rent_due_day}} day of each month.
**Payment Methods:** Check, money order, or approved electronic payment.

---

## 4. LATE FEES

**Grace Period:** {{grace_period_days}} days
**Late Fee:** {{late_fee_amount}} if rent is not received within the grace period.

---

## 5. SECURITY DEPOSIT

**Amount:** {{security_deposit}}

The security deposit will be held as security for the faithful performance of Tenant's obligations and will be returned within the time period required by law after termination, less any lawful deductions.

---

## 6. UTILITIES

**Included by Landlord:** {{utilities_included}}

Tenant is responsible for all other utilities and must maintain service throughout the tenancy.

---

## 7. OCCUPANTS

**Authorized Occupants:** {{all_occupant_names}}
**Maximum Occupants:** {{max_occupants}}

Only authorized occupants may reside in the premises.

---

## 8. PETS

**Pets Allowed:** {{pets_allowed}}
**Maximum Pets:** {{max_pets}}

If pets are permitted, a separate Pet Addendum must be signed.

---

## 9. SMOKING

**Smoking Permitted:** {{smoking_allowed}}

---

## 10. MAINTENANCE

Tenant agrees to maintain the premises in clean and sanitary condition and to promptly report any needed repairs to Landlord.

---

## 11. ENTRY BY LANDLORD

Landlord may enter the premises with at least 24 hours' notice for inspections, repairs, or to show the property. In emergencies, Landlord may enter without notice.

---

## 12. RENT INCREASES

Landlord may increase the rent by providing written notice at least **30 days** before the effective date of the increase.

---

## 13. GOVERNING LAW

This Agreement shall be governed by the laws of the State of {{property_state}}.

---

## SIGNATURES

By signing below, the parties agree to all terms and conditions of this Month-to-Month Rental Agreement.

**LANDLORD:**

[SIGNATURE:Landlord]

Date: _______________

**TENANT:**

[SIGNATURE:Tenant]

Date: _______________

---

*Generated by PropManager on {{current_date}}*
"""

LEASE_RENEWAL_AGREEMENT = """# LEASE RENEWAL AGREEMENT

This Lease Renewal Agreement ("Agreement") is entered into on {{current_date}} between:

**LANDLORD:** {{landlord_name}}
**TENANT(S):** {{tenant_name}}

---

## 1. ORIGINAL LEASE

This Agreement renews and extends the original Residential Lease Agreement dated _____________ for the property located at:

**Address:** {{property_address}}
**Unit:** {{unit_number}}

---

## 2. RENEWAL TERM

The original Lease is hereby renewed for a period of:

**New Start Date:** {{lease_start_date}}
**New End Date:** {{lease_end_date}}

---

## 3. RENT

The monthly rent for the renewal term shall be:

**Monthly Rent:** {{monthly_rent}}
**Due Date:** The {{rent_due_day}} day of each month

---

## 4. SECURITY DEPOSIT

The security deposit currently held shall remain on deposit and continue to be held as security for the renewal term.

**Current Security Deposit:** {{security_deposit}}

[ ] No additional deposit required
[ ] Additional deposit of $_________ required

---

## 5. CHANGES TO ORIGINAL LEASE

Except as specifically modified by this Agreement, all other terms and conditions of the original Lease shall remain in full force and effect during the renewal term.

**Additional modifications (if any):**

_________________________________________________________________

_________________________________________________________________

---

## 6. ACKNOWLEDGMENT

Both parties acknowledge that:

1. The Tenant is current on all rent and other payments
2. There are no outstanding violations of the original Lease
3. The premises are in acceptable condition
4. All terms of this renewal have been discussed and agreed upon

---

## SIGNATURES

By signing below, the parties agree to renew the Lease under the terms stated above.

**LANDLORD:**

[SIGNATURE:Landlord]

Date: _______________

**TENANT:**

[SIGNATURE:Tenant]

Date: _______________

---

*Generated by PropManager on {{current_date}}*
"""

GUARANTOR_AGREEMENT = """# GUARANTOR / CO-SIGNER AGREEMENT

This Guarantor Agreement ("Agreement") is entered into on {{current_date}}.

---

## 1. PARTIES

**LANDLORD:** {{landlord_name}}

**TENANT:** {{tenant_name}}

**GUARANTOR:** _________________________________ ("Guarantor")

---

## 2. PREMISES

This Agreement relates to the lease of the property located at:

**Address:** {{property_address}}
**Unit:** {{unit_number}}

---

## 3. LEASE TERMS

**Lease Start Date:** {{lease_start_date}}
**Lease End Date:** {{lease_end_date}}
**Monthly Rent:** {{monthly_rent}}
**Security Deposit:** {{security_deposit}}

---

## 4. GUARANTEE

In consideration of Landlord entering into a lease agreement with Tenant, Guarantor hereby unconditionally and irrevocably guarantees:

1. **Payment of Rent:** The full and prompt payment of all rent due under the Lease
2. **Other Charges:** Payment of all other charges, fees, and amounts due under the Lease
3. **Damages:** Payment for any damages to the premises caused by Tenant beyond normal wear and tear
4. **Legal Costs:** Payment of any legal fees and costs incurred by Landlord in enforcing this Agreement

---

## 5. NATURE OF GUARANTEE

This is a guarantee of payment, not collection. Landlord may proceed directly against Guarantor without first pursuing Tenant. Guarantor's obligations are:

- **Absolute and unconditional**
- **Not affected by** any modification of the Lease
- **Not released by** any extension of time granted to Tenant
- **Not discharged by** Tenant's bankruptcy or incapacity

---

## 6. TERM

This Guarantee shall continue in effect for the full term of the Lease, including any renewals or extensions, and until all obligations have been satisfied.

---

## 7. WAIVER

Guarantor waives:

- Notice of acceptance of this Guarantee
- Notice of any default by Tenant
- Any right to require Landlord to proceed against Tenant first
- Any other notices required by law

---

## 8. GUARANTOR INFORMATION

**Full Legal Name:** _________________________________

**Date of Birth:** _________________________________

**Social Security Number (last 4 digits):** XXX-XX-____

**Current Address:**

_________________________________

_________________________________

**Phone:** _________________________________

**Email:** _________________________________

**Employer:** _________________________________

**Annual Income:** $_________________________________

---

## 9. ACKNOWLEDGMENT

Guarantor acknowledges that:

1. Guarantor has read the Lease Agreement in its entirety
2. Guarantor understands the obligations being guaranteed
3. Guarantor has the financial means to fulfill this Guarantee
4. Guarantor is signing this Agreement voluntarily

---

## SIGNATURES

**LANDLORD:**

[SIGNATURE:Landlord]

Date: _______________

**TENANT:**

[SIGNATURE:Tenant]

Date: _______________

**GUARANTOR:**

[SIGNATURE:Cosigner]

Date: _______________

---

*Generated by PropManager on {{current_date}}*
"""

ROOMMATE_AGREEMENT = """# ROOMMATE AGREEMENT

This Roommate Agreement ("Agreement") is entered into on {{current_date}}.

---

## 1. PREMISES

This Agreement applies to the rental property located at:

**Address:** {{property_address}}
**Unit:** {{unit_number}}

---

## 2. ROOMMATES

The following individuals are parties to this Agreement:

**Primary Tenant:** {{tenant_name}}

**Roommate(s):**

1. _________________________________

2. _________________________________

3. _________________________________

---

## 3. TERM

This Agreement shall be effective from {{lease_start_date}} through {{lease_end_date}}, or until terminated as provided herein.

---

## 4. RENT DIVISION

**Total Monthly Rent:** {{monthly_rent}}

Each roommate agrees to pay their share as follows:

| Roommate | Monthly Share | Due Date |
|----------|---------------|----------|
| {{tenant_name}} | $_________ | {{rent_due_day}} |
| ________________ | $_________ | {{rent_due_day}} |
| ________________ | $_________ | {{rent_due_day}} |

**Payment Coordinator:** _________________________________ will collect all payments and submit to Landlord.

---

## 5. SECURITY DEPOSIT

**Total Security Deposit:** {{security_deposit}}

Each roommate has contributed:

| Roommate | Deposit Contribution |
|----------|---------------------|
| {{tenant_name}} | $_________ |
| ________________ | $_________ |
| ________________ | $_________ |

---

## 6. UTILITIES

Monthly utilities will be divided as follows:

| Utility | Responsible Party | Division Method |
|---------|------------------|-----------------|
| Electric | ______________ | [ ] Equal [ ] Usage |
| Gas | ______________ | [ ] Equal [ ] Usage |
| Water | ______________ | [ ] Equal [ ] Usage |
| Internet | ______________ | [ ] Equal [ ] Usage |
| Cable/Streaming | ______________ | [ ] Equal [ ] Usage |

---

## 7. BEDROOM ASSIGNMENTS

| Roommate | Bedroom/Room |
|----------|--------------|
| {{tenant_name}} | ______________ |
| ________________ | ______________ |
| ________________ | ______________ |

---

## 8. COMMON AREAS

All roommates share equal access to and responsibility for:

- Living room
- Kitchen
- Bathroom(s)
- Other: _________________________________

---

## 9. HOUSEHOLD RULES

**Quiet Hours:** _________ PM to _________ AM

**Guests:**
- Overnight guests allowed: [ ] Yes [ ] No
- Maximum consecutive nights: _________
- Guest must be approved by: [ ] All roommates [ ] Majority

**Cleaning:**
- Common areas cleaned: [ ] Weekly [ ] Bi-weekly
- Cleaning schedule: [ ] Rotating [ ] Assigned

**Smoking:** [ ] Allowed [ ] Not allowed [ ] Designated area only

**Pets:** [ ] Allowed [ ] Not allowed
If allowed, specify: _________________________________

**Parties/Gatherings:** Require [ ] 24 hours [ ] 48 hours [ ] 1 week notice

---

## 10. FOOD AND SUPPLIES

[ ] All food is shared equally
[ ] Each roommate keeps separate food
[ ] Shared items: _________________________________

Shared household supplies (toilet paper, cleaning supplies, etc.) will be:
[ ] Purchased on a rotating basis
[ ] Split equally each month
[ ] Purchased by: _________________________________

---

## 11. CONFLICT RESOLUTION

Roommates agree to:

1. Discuss issues directly and respectfully
2. Hold house meetings as needed
3. If unresolved, seek mediation before involving Landlord
4. Comply with all terms of the master Lease Agreement

---

## 12. TERMINATION

A roommate wishing to leave must:

1. Provide at least **30 days** written notice to all other roommates
2. Find an acceptable replacement (subject to Landlord approval)
3. Continue paying their share until a replacement moves in
4. Settle all outstanding balances

---

## 13. MASTER LEASE

All roommates acknowledge they have read and agree to comply with the master Lease Agreement with the Landlord. This Roommate Agreement does not replace the Lease but supplements it.

---

## SIGNATURES

All parties agree to the terms of this Roommate Agreement:

**Roommate 1:**

[SIGNATURE:Tenant]

Date: _______________

**Roommate 2:**

[SIGNATURE:Tenant2]

Date: _______________

**Roommate 3:**

[SIGNATURE:Tenant3]

Date: _______________

---

*Generated by PropManager on {{current_date}}*
"""


# =============================================================================
# ADDENDUMS
# =============================================================================

PET_ADDENDUM = """# PET ADDENDUM

This Pet Addendum ("Addendum") is attached to and made part of the Lease Agreement dated {{lease_start_date}} between:

**LANDLORD:** {{landlord_name}}
**TENANT:** {{tenant_name}}

For the property located at: {{property_address}}, Unit {{unit_number}}

---

## 1. PET AUTHORIZATION

Landlord grants permission for Tenant to keep the following pet(s) on the premises:

| Pet # | Type | Breed | Name | Color | Weight | Age |
|-------|------|-------|------|-------|--------|-----|
| 1 | _____ | _____ | _____ | _____ | _____ lbs | _____ |
| 2 | _____ | _____ | _____ | _____ | _____ lbs | _____ |

**Maximum Pets Allowed:** {{max_pets}}

---

## 2. PET DEPOSIT AND FEES

**Pet Deposit:** $_________ (refundable)

**Monthly Pet Rent:** $_________ per pet

**Non-Refundable Pet Fee:** $_________

---

## 3. VACCINATION AND LICENSING

Tenant agrees to:

1. Keep all pets current on vaccinations as required by law
2. Provide proof of vaccinations upon request
3. Maintain current pet licenses as required by local ordinances
4. Dogs must have current rabies vaccination

---

## 4. PET RULES AND RESPONSIBILITIES

Tenant agrees to the following:

**General Care:**
- Keep pets properly fed, watered, and cared for
- Not leave pets unattended for extended periods
- Keep pets clean and free of parasites

**Behavior:**
- Pets must not disturb neighbors through excessive noise
- Dogs must be leashed when outside the unit
- Pets must be under control at all times

**Waste:**
- Clean up pet waste immediately in all areas
- Properly dispose of waste in designated receptacles
- Do not allow pet waste to accumulate

**Property:**
- Do not allow pets to damage any part of the property
- Tenant is responsible for all pet-related damages
- No pets allowed in common areas unless passing through

---

## 5. PROHIBITED ACTIVITIES

Tenant shall NOT:

- Keep more pets than authorized
- Breed or raise pets for commercial purposes
- Allow pets to roam freely outside the unit
- Keep prohibited breeds or species (check local laws)
- Allow pet waste to create unsanitary conditions

---

## 6. LIABILITY

Tenant assumes full responsibility for:

1. Any injury caused by pet(s) to any person
2. Any damage caused by pet(s) to the property or others' property
3. Any noise or nuisance complaints related to pet(s)
4. All costs of repair or cleaning due to pet(s)

Tenant agrees to maintain renter's insurance that includes pet liability coverage.

---

## 7. REMOVAL OF PET

Landlord may require removal of pet(s) if:

1. Pet causes damage to the property
2. Pet creates a nuisance or disturbs neighbors
3. Pet poses a health or safety risk
4. Tenant violates any terms of this Addendum
5. Pet is not properly licensed or vaccinated

Upon written notice, Tenant shall have **7 days** to remove the pet or remedy the violation.

---

## 8. ADDITIONAL TERMS

_________________________________________________________________

_________________________________________________________________

---

## SIGNATURES

**LANDLORD:**

[SIGNATURE:Landlord]

Date: _______________

**TENANT:**

[SIGNATURE:Tenant]

Date: _______________

---

*Generated by PropManager on {{current_date}}*
"""

PARKING_ADDENDUM = """# PARKING ADDENDUM

This Parking Addendum ("Addendum") is attached to and made part of the Lease Agreement dated {{lease_start_date}} between:

**LANDLORD:** {{landlord_name}}
**TENANT:** {{tenant_name}}

For the property located at: {{property_address}}, Unit {{unit_number}}

---

## 1. PARKING SPACE ASSIGNMENT

Tenant is assigned the following parking space(s):

**Number of Spaces:** {{parking_spaces}}
**Space Number(s):** {{parking_space_numbers}}
**Location:** _________________________________

---

## 2. PARKING FEES

[ ] Parking is included in rent at no additional charge
[ ] Monthly Parking Fee: $_________ per space
[ ] Parking Deposit: $_________ (refundable)

---

## 3. VEHICLE REGISTRATION

Only the following vehicle(s) may use the assigned space(s):

| Vehicle # | Make | Model | Year | Color | License Plate | State |
|-----------|------|-------|------|-------|---------------|-------|
| 1 | _____ | _____ | _____ | _____ | _____ | _____ |
| 2 | _____ | _____ | _____ | _____ | _____ | _____ |

Tenant must notify Landlord of any vehicle changes within **7 days**.

---

## 4. PARKING RULES

**Permitted:**
- Registered passenger vehicles only
- Motorcycles (if designated)
- Properly maintained and licensed vehicles

**Prohibited:**
- Commercial vehicles (unless pre-approved)
- Recreational vehicles (RVs, campers)
- Boats and trailers
- Inoperable or unregistered vehicles
- Vehicles leaking fluids
- Oversized vehicles exceeding space boundaries

---

## 5. VEHICLE REQUIREMENTS

All vehicles must:

1. Have current registration and license plates
2. Be in operable condition
3. Have valid insurance
4. Not leak oil, fluids, or hazardous materials
5. Fit within the assigned space boundaries

---

## 6. GUEST PARKING

Guest parking is:

[ ] Available in designated visitor spaces
[ ] Limited to _________ hours
[ ] By permit only (obtain from office)
[ ] Not available on premises

---

## 7. PARKING VIOLATIONS

The following violations may result in towing at owner's expense:

- Parking in unauthorized spaces
- Blocking other vehicles or access ways
- Parking in fire lanes or handicapped spaces (without permit)
- Abandoned or inoperable vehicles
- Repeated violations of parking rules

**Warning:** Vehicles in violation may be towed without notice in emergency situations.

---

## 8. LIABILITY

- Landlord is not responsible for theft, vandalism, or damage to vehicles
- Tenant parks at their own risk
- Tenant is responsible for any damage caused by their vehicle

---

## 9. RESERVED RIGHTS

Landlord reserves the right to:

1. Reassign parking spaces with reasonable notice
2. Temporarily close parking areas for maintenance
3. Modify parking rules with 30 days' notice
4. Tow unauthorized vehicles

---

## SIGNATURES

**LANDLORD:**

[SIGNATURE:Landlord]

Date: _______________

**TENANT:**

[SIGNATURE:Tenant]

Date: _______________

---

*Generated by PropManager on {{current_date}}*
"""

NO_SMOKING_ADDENDUM = """# SMOKE-FREE PROPERTY ADDENDUM

This Smoke-Free Property Addendum ("Addendum") is attached to and made part of the Lease Agreement dated {{lease_start_date}} between:

**LANDLORD:** {{landlord_name}}
**TENANT:** {{tenant_name}}

For the property located at: {{property_address}}, Unit {{unit_number}}

---

## 1. PURPOSE

The parties desire to promote a healthier living environment for all residents. This Addendum establishes smoke-free standards for the premises.

---

## 2. DEFINITIONS

**"Smoking"** means inhaling, exhaling, burning, or carrying any lighted or heated:

- Cigarettes
- Cigars
- Pipes
- Hookah
- Electronic cigarettes (e-cigarettes, vapes)
- Any other smoking device or product

---

## 3. SMOKE-FREE AREAS

Smoking is **PROHIBITED** in the following areas:

**Inside the Unit:**
[X] All rooms and enclosed spaces
[X] Balconies and patios
[X] Attached garages

**Common Areas:**
[X] Hallways and stairways
[X] Laundry facilities
[X] Community rooms
[X] Parking structures
[X] Within 25 feet of windows, doors, and air intakes

**Outdoor Areas:**
[ ] Entire property grounds
[X] Pools and recreation areas
[ ] Designated smoking areas only

---

## 4. TENANT RESPONSIBILITIES

Tenant agrees to:

1. **Not smoke** in any prohibited areas
2. **Inform guests** of the smoke-free policy
3. **Ensure all occupants and guests** comply with this policy
4. **Report violations** to Landlord promptly
5. **Not permit** smoking odors to infiltrate other units

---

## 5. GUEST COMPLIANCE

Tenant is responsible for ensuring all guests comply with this Addendum. Repeated guest violations will be treated as Tenant violations.

---

## 6. DESIGNATED SMOKING AREAS

[ ] No designated smoking areas on property
[ ] Smoking permitted only in: _________________________________

If designated areas exist, smokers must:
- Properly dispose of smoking materials
- Keep area clean
- Not block access points

---

## 7. ENFORCEMENT AND VIOLATIONS

**First Violation:** Written warning
**Second Violation:** $_________ fine
**Third Violation:** $_________ fine and lease termination process may begin

Landlord may also charge Tenant for:
- Deep cleaning required due to smoke odor
- Repairs to smoke-damaged surfaces
- Air quality restoration
- Any third-party complaints or damages

---

## 8. DISCLAIMER

Landlord's adoption of a smoke-free policy does not:

- Make Landlord a guarantor of tenant health
- Guarantee compliance by all tenants
- Create liability for smoke that migrates despite the policy

---

## 9. ACKNOWLEDGMENT

Tenant acknowledges:

1. Understanding the smoke-free policy
2. Agreeing to comply and ensure guest compliance
3. Understanding that violation may result in lease termination
4. Having received a copy of this Addendum

---

## SIGNATURES

**LANDLORD:**

[SIGNATURE:Landlord]

Date: _______________

**TENANT:**

[SIGNATURE:Tenant]

Date: _______________

---

*Generated by PropManager on {{current_date}}*
"""

SMOKE_CO_DETECTOR_ADDENDUM = """# SMOKE AND CARBON MONOXIDE DETECTOR ADDENDUM

This Addendum is attached to and made part of the Lease Agreement dated {{lease_start_date}} between:

**LANDLORD:** {{landlord_name}}
**TENANT:** {{tenant_name}}

For the property located at: {{property_address}}, Unit {{unit_number}}

---

## 1. PURPOSE

This Addendum confirms that working smoke and carbon monoxide detectors have been installed in the rental unit and outlines the responsibilities of both parties.

---

## 2. DETECTOR LOCATIONS

The following detectors have been installed and tested:

**Smoke Detectors:**

| Location | Type | Tested | Working |
|----------|------|--------|---------|
| _________________ | [ ] Battery [ ] Hardwired | [ ] Yes | [ ] Yes |
| _________________ | [ ] Battery [ ] Hardwired | [ ] Yes | [ ] Yes |
| _________________ | [ ] Battery [ ] Hardwired | [ ] Yes | [ ] Yes |
| _________________ | [ ] Battery [ ] Hardwired | [ ] Yes | [ ] Yes |

**Carbon Monoxide Detectors:**

| Location | Type | Tested | Working |
|----------|------|--------|---------|
| _________________ | [ ] Battery [ ] Hardwired | [ ] Yes | [ ] Yes |
| _________________ | [ ] Battery [ ] Hardwired | [ ] Yes | [ ] Yes |

---

## 3. LANDLORD RESPONSIBILITIES

Landlord agrees to:

1. Install smoke detectors as required by state and local law
2. Install carbon monoxide detectors as required by law
3. Test all detectors before tenant move-in
4. Provide working batteries at move-in
5. Replace detectors that are defective or beyond useful life
6. Respond promptly to reported detector issues

---

## 4. TENANT RESPONSIBILITIES

Tenant agrees to:

1. **Test detectors monthly** by pressing the test button
2. **Replace batteries** as needed (unless hardwired)
3. **Never disable, disconnect, or remove** any detector
4. **Report malfunctions** to Landlord immediately
5. **Allow access** for Landlord to inspect or repair detectors
6. **Keep detectors** free from paint, dirt, or obstructions
7. **Know evacuation routes** in case of emergency

---

## 5. BATTERY REPLACEMENT

**Battery-operated detectors:**
- Tenant shall replace batteries at least once per year
- Tenant shall replace batteries immediately if low-battery signal sounds

**Landlord shall provide:**
[ ] Initial batteries at move-in
[ ] Replacement batteries upon request
[ ] Batteries are Tenant's responsibility

---

## 6. TESTING CONFIRMATION

Tenant confirms that on {{current_date}}:

[ ] All smoke detectors were tested and are working
[ ] All carbon monoxide detectors were tested and are working
[ ] Tenant understands how to test the detectors
[ ] Tenant knows the location of all detectors

---

## 7. PROHIBITED ACTIONS

Tenant shall NOT:

- Remove batteries (except for replacement)
- Disable or disconnect any detector
- Cover or paint over detectors
- Hang items from detectors
- Ignore low-battery warnings

---

## 8. CONSEQUENCES OF VIOLATION

Disabling or removing smoke or carbon monoxide detectors:

1. May violate state and local law
2. Puts lives at risk
3. May void renter's insurance coverage
4. Is grounds for lease termination
5. May result in Tenant liability for damages

---

## 9. EMERGENCY PROCEDURES

In case of alarm:

1. Evacuate the premises immediately
2. Call 911 from outside the building
3. Do not re-enter until cleared by authorities
4. Notify Landlord after ensuring safety

---

## SIGNATURES

By signing below, Tenant acknowledges receiving this Addendum and confirms all detectors are in working condition.

**LANDLORD:**

[SIGNATURE:Landlord]

Date: _______________

**TENANT:**

[SIGNATURE:Tenant]

Date: _______________

---

*Generated by PropManager on {{current_date}}*
"""

BED_BUG_ADDENDUM = """# BED BUG ADDENDUM

This Bed Bug Addendum ("Addendum") is attached to and made part of the Lease Agreement dated {{lease_start_date}} between:

**LANDLORD:** {{landlord_name}}
**TENANT:** {{tenant_name}}

For the property located at: {{property_address}}, Unit {{unit_number}}

---

## 1. DISCLOSURE

**Property History:**
[ ] Landlord has no knowledge of any bed bug infestation in this unit
[ ] This unit was previously treated for bed bugs on: _____________
[ ] The building has had bed bug issues in other units

**Current Status:**
The unit has been inspected and no evidence of bed bugs was found as of {{current_date}}.

---

## 2. WHAT ARE BED BUGS?

Bed bugs are small, flat, parasitic insects that feed on human blood. They are:

- Reddish-brown, oval, and about the size of an apple seed
- Typically found in mattresses, box springs, bed frames, and furniture
- Can travel between units through walls, floors, and ceilings
- Not a sign of uncleanliness but spread through human activity

---

## 3. TENANT ACKNOWLEDGMENT

Tenant acknowledges:

[ ] Receiving information about bed bug identification and prevention
[ ] The unit was inspected before move-in and no bed bugs were found
[ ] Understanding the importance of immediate reporting
[ ] Agreeing to cooperate with any treatment efforts

---

## 4. TENANT RESPONSIBILITIES

Tenant agrees to:

**Prevention:**
- Inspect used furniture, clothing, and luggage before bringing into the unit
- Use protective mattress and box spring encasements
- Reduce clutter where bed bugs can hide
- Vacuum regularly

**Reporting:**
- Report any suspected bed bug activity to Landlord within **24 hours**
- Provide access for inspection upon reasonable notice
- Do NOT attempt to treat bed bugs without Landlord's written consent

**During Treatment:**
- Follow all preparation instructions provided by the pest control company
- Cooperate with all treatment protocols
- Remain out of the unit during treatment if required
- Follow post-treatment instructions

---

## 5. LANDLORD RESPONSIBILITIES

Upon receiving a bed bug report, Landlord will:

1. Arrange for professional inspection within **48 hours**
2. If infestation confirmed, arrange treatment promptly
3. Treat adjacent units if recommended by pest control
4. Provide written preparation instructions
5. Schedule follow-up inspections as needed

---

## 6. TREATMENT COSTS

**If bed bugs are found:**

[ ] Landlord pays for all treatment costs
[ ] Costs will be shared based on determination of source
[ ] Tenant pays if infestation resulted from Tenant's actions

**Tenant may be responsible for costs if:**
- Bed bugs were introduced by Tenant's belongings
- Tenant failed to report promptly
- Tenant did not follow preparation or treatment instructions
- Tenant refused access for inspection or treatment

---

## 7. PROHIBITED ACTIONS

Tenant shall NOT:

- Use over-the-counter pesticides or "bug bombs"
- Move furniture or belongings to other units
- Dispose of infested items without proper wrapping
- Refuse access for inspection or treatment
- Fail to follow preparation instructions

---

## 8. LIABILITY

Tenant may be held liable for:

- Costs of treatment if bed bugs resulted from Tenant's actions
- Damage to neighboring units from spreading infestation
- Any costs resulting from failure to report or cooperate

---

## 9. LEASE TERMINATION

Landlord may terminate the lease if Tenant:

- Fails to report suspected bed bugs
- Refuses to allow inspection or treatment
- Does not cooperate with treatment protocols
- Introduces bed bugs through repeated negligent behavior

---

## SIGNATURES

**LANDLORD:**

[SIGNATURE:Landlord]

Date: _______________

**TENANT:**

[SIGNATURE:Tenant]

Date: _______________

---

*Generated by PropManager on {{current_date}}*
"""


# =============================================================================
# DISCLOSURES
# =============================================================================

LEAD_PAINT_DISCLOSURE = """# LEAD-BASED PAINT DISCLOSURE

## Disclosure of Information on Lead-Based Paint and/or Lead-Based Paint Hazards

**Property Address:** {{property_address}}, Unit {{unit_number}}

This disclosure is required by federal law for housing built before 1978.

---

## LEAD WARNING STATEMENT

Housing built before 1978 may contain lead-based paint. Lead from paint, paint chips, and dust can pose health hazards if not managed properly. Lead exposure is especially harmful to young children and pregnant women.

Before renting pre-1978 housing, landlords must disclose the presence of known lead-based paint and/or lead-based paint hazards in the dwelling. Tenants must also receive a federally approved pamphlet on lead poisoning prevention.

---

## LANDLORD'S DISCLOSURE

**Check all that apply:**

**Presence of Lead-Based Paint:**

[ ] **(a)** Landlord has no knowledge of lead-based paint and/or lead-based paint hazards in the housing.

[ ] **(b)** Landlord has knowledge of lead-based paint and/or lead-based paint hazards in the housing. Explain:

_________________________________________________________________

_________________________________________________________________

**Records and Reports:**

[ ] **(c)** Landlord has no reports or records pertaining to lead-based paint and/or lead-based paint hazards in the housing.

[ ] **(d)** Landlord has provided the tenant with all available records and reports pertaining to lead-based paint and/or lead-based paint hazards in the housing. List documents:

_________________________________________________________________

_________________________________________________________________

---

## TENANT'S ACKNOWLEDGMENT

**Initial each statement:**

_____ **(e)** Tenant has received copies of all information listed above.

_____ **(f)** Tenant has received the pamphlet "Protect Your Family From Lead in Your Home."

---

## AGENT'S ACKNOWLEDGMENT (if applicable)

_____ **(g)** Agent has informed the landlord of the landlord's obligations under 42 U.S.C. 4852d and is aware of his/her responsibility to ensure compliance.

---

## CERTIFICATION OF ACCURACY

The following parties have reviewed the information above and certify, to the best of their knowledge, that the information provided is true and accurate.

**LANDLORD:**

[SIGNATURE:Landlord]

Printed Name: _________________________________

Date: _______________

**TENANT:**

[SIGNATURE:Tenant]

Printed Name: {{tenant_name}}

Date: _______________

---

## IMPORTANT INFORMATION

For more information about lead poisoning and how to protect your family:

- Call the National Lead Information Center at 1-800-424-LEAD
- Visit www.epa.gov/lead
- Contact your local health department

---

*This form complies with Section 1018 of the Residential Lead-Based Paint Hazard Reduction Act of 1992.*

*Generated by PropManager on {{current_date}}*
"""

MOLD_DISCLOSURE = """# MOLD INFORMATION AND DISCLOSURE

This Mold Disclosure ("Disclosure") is provided in connection with the Lease Agreement dated {{lease_start_date}} between:

**LANDLORD:** {{landlord_name}}
**TENANT:** {{tenant_name}}

For the property located at: {{property_address}}, Unit {{unit_number}}

---

## 1. DISCLOSURE OF KNOWN MOLD

**Check one:**

[ ] Landlord has NO KNOWLEDGE of mold or mold conditions in the unit.

[ ] Landlord has knowledge of the following mold conditions:

_________________________________________________________________

_________________________________________________________________

**Previous remediation (if applicable):**

[ ] No previous mold remediation
[ ] Mold was remediated on: _____________
    Location: _________________________________
    Work performed: _________________________________

---

## 2. WHAT IS MOLD?

Mold is a type of fungus that can grow indoors and outdoors. It reproduces through tiny spores that float through the air and can grow on almost any surface when moisture is present.

**Common types include:**
- Cladosporium
- Penicillium
- Aspergillus
- Alternaria
- Stachybotrys ("black mold")

---

## 3. HEALTH EFFECTS

Exposure to mold may cause:

- Allergic reactions (sneezing, runny nose, red eyes, skin rash)
- Asthma attacks in people with asthma
- Respiratory irritation
- In severe cases, more serious health problems

**Individuals at higher risk:**
- Infants and children
- Elderly persons
- Individuals with respiratory conditions
- Individuals with weakened immune systems
- Pregnant women

---

## 4. CONDITIONS THAT PROMOTE MOLD GROWTH

Mold requires moisture to grow. Common sources include:

- Water leaks (roof, plumbing, windows)
- Flooding
- High humidity
- Condensation
- Poor ventilation
- Wet clothes or materials
- Overwatering plants

---

## 5. LANDLORD RESPONSIBILITIES

Landlord agrees to:

1. Address water intrusion and leaks promptly
2. Maintain adequate ventilation in the unit
3. Respond to mold reports within a reasonable time
4. Arrange for professional assessment if needed
5. Remediate significant mold growth professionally

---

## 6. TENANT RESPONSIBILITIES

Tenant agrees to:

**Report Immediately:**
- Any water leaks or intrusion
- Visible mold growth (any color)
- Musty or moldy odors
- Condensation on windows or walls
- Plumbing problems
- HVAC issues

**Prevent Moisture:**
- Use exhaust fans when cooking and bathing
- Ensure adequate ventilation
- Keep humidity below 60%
- Wipe down wet surfaces
- Not block air vents
- Clean and dry spills promptly
- Report air conditioning drips

**Do NOT:**
- Attempt to clean large mold areas without approval
- Use bleach without proper precautions
- Cover mold with paint
- Ignore signs of water damage

---

## 7. CONSEQUENCES OF FAILURE TO REPORT

Tenant may be held responsible for mold damage if:

- Tenant fails to report water problems or visible mold
- Tenant's actions or negligence caused the moisture
- Tenant fails to maintain reasonable humidity levels
- Tenant obstructs ventilation

---

## 8. TENANT ACKNOWLEDGMENT

Tenant acknowledges:

[ ] Reading and understanding this Mold Disclosure
[ ] Inspecting the unit and finding no visible mold at move-in
[ ] Understanding the obligation to report water/mold issues immediately
[ ] Agreeing to take reasonable steps to prevent mold growth

---

## SIGNATURES

**LANDLORD:**

[SIGNATURE:Landlord]

Date: _______________

**TENANT:**

[SIGNATURE:Tenant]

Date: _______________

---

*Generated by PropManager on {{current_date}}*
"""


# =============================================================================
# NOTICES
# =============================================================================

NOTICE_TO_VACATE = """# NOTICE TO VACATE

**Date:** {{current_date}}

**To:** {{tenant_name}}
**Property Address:** {{property_address}}, Unit {{unit_number}}

---

## NOTICE OF INTENT TO VACATE

This letter serves as formal notice that I/we, the undersigned tenant(s), intend to vacate the above-referenced premises.

**Move-Out Date:** _________________________________

**Forwarding Address for Security Deposit Return:**

_________________________________

_________________________________

_________________________________

**Phone:** _________________________________

**Email:** _________________________________

---

## REASON FOR VACATING

[ ] End of lease term
[ ] Relocating for employment
[ ] Purchasing a home
[ ] Personal/family reasons
[ ] Other: _________________________________

---

## MOVE-OUT PROCEDURES

I/We understand and agree to:

1. **Return all keys** (including mailbox, gate, garage) by the move-out date
2. **Remove all personal belongings** and dispose of all trash
3. **Clean the unit** thoroughly, including:
   - Cleaning all appliances inside and out
   - Cleaning all cabinets and drawers
   - Cleaning bathrooms, including tub, toilet, and sink
   - Vacuuming/mopping all floors
   - Cleaning windows and blinds
   - Removing all nails/hooks and filling holes
4. **Repair any damage** beyond normal wear and tear
5. **Transfer utilities** out of my name as of the move-out date
6. **Provide forwarding address** for security deposit return

---

## MOVE-OUT INSPECTION

[ ] I request to be present during the move-out inspection
[ ] I waive my right to be present during the inspection

**Preferred inspection date/time:** _________________________________

---

## SECURITY DEPOSIT

I understand that my security deposit of {{security_deposit}} will be returned, less any lawful deductions, within the time period required by state law. Deductions may include:

- Unpaid rent or fees
- Cleaning costs if unit is not left in move-in condition
- Repair costs for damage beyond normal wear and tear
- Unreturned keys or access devices

---

## ACKNOWLEDGMENT

I confirm that I have read and understand my move-out obligations and agree to comply with all requirements of my lease agreement.

**TENANT:**

[SIGNATURE:Tenant]

Printed Name: {{tenant_name}}

Date: _______________

---

*Please return this form to:*

{{landlord_name}}
{{office_address}}

---

*Generated by PropManager on {{current_date}}*
"""

RENT_INCREASE_NOTICE = """# NOTICE OF RENT INCREASE

**Date:** {{current_date}}

**To:** {{tenant_name}}
**Property Address:** {{property_address}}, Unit {{unit_number}}

---

Dear {{tenant_name}},

This letter serves as formal notice that your monthly rent will be increased effective **[EFFECTIVE DATE]**.

---

## RENT CHANGE DETAILS

| | Current | New |
|---|---------|-----|
| **Monthly Rent** | {{monthly_rent}} | $_________ |
| **Increase Amount** | -- | $_________ |
| **Percentage Increase** | -- | _____% |

**Effective Date:** _________________________________

---

## REASON FOR INCREASE

[ ] Annual adjustment for operating costs
[ ] Property tax increase
[ ] Insurance cost increase
[ ] Maintenance and improvement costs
[ ] Market rate adjustment
[ ] Other: _________________________________

---

## PAYMENT INSTRUCTIONS

Starting on the effective date above:

- Your new monthly rent will be: $_________
- Rent is due on the {{rent_due_day}} day of each month
- Payment methods remain unchanged
- All other lease terms remain in effect

---

## YOUR OPTIONS

You may:

**1. Accept the increase** - Continue your tenancy at the new rate. No action required.

**2. Discuss the increase** - Contact us to discuss:
   - Phone: {{manager_phone}}
   - Email: {{manager_email}}

**3. Provide notice to vacate** - If you choose not to continue at the new rate, please provide written notice according to your lease terms (typically 30 days for month-to-month).

---

## LEGAL NOTICE

This notice is provided in accordance with state and local law, which requires a minimum of **[30/60/90] days** notice before a rent increase takes effect.

---

## APPRECIATION

We value you as a tenant and hope you will continue your tenancy with us. If you have any questions about this notice, please don't hesitate to contact our office.

Sincerely,

**LANDLORD/PROPERTY MANAGER:**

[SIGNATURE:Landlord]

{{landlord_name}}

---

## TENANT ACKNOWLEDGMENT (Optional)

I have received this Notice of Rent Increase and understand the new rent amount effective on the date stated.

**TENANT:**

[SIGNATURE:Tenant]

Date: _______________

---

*Generated by PropManager on {{current_date}}*
"""

NOTICE_OF_ENTRY = """# NOTICE OF ENTRY

**Date:** {{current_date}}

**To:** {{tenant_name}}
**Property Address:** {{property_address}}, Unit {{unit_number}}

---

## NOTICE OF INTENT TO ENTER

This notice is to inform you that the Landlord or authorized representative will enter your rental unit on:

**Date of Entry:** _________________________________

**Time of Entry:** _________________________________

**Estimated Duration:** _________________________________

---

## PURPOSE OF ENTRY

[ ] Routine inspection
[ ] Maintenance/repairs
[ ] Pest control treatment
[ ] Show unit to prospective tenants
[ ] Show unit to prospective buyers
[ ] Emergency repairs
[ ] Check smoke/CO detectors
[ ] HVAC maintenance
[ ] Other: _________________________________

---

## DESCRIPTION OF WORK/ACTIVITY

_________________________________________________________________

_________________________________________________________________

_________________________________________________________________

---

## PERSONS WHO MAY ENTER

[ ] Landlord/Property Manager
[ ] Maintenance personnel
[ ] Contractor: _________________________________
[ ] Pest control technician
[ ] Inspector
[ ] Real estate agent
[ ] Other: _________________________________

---

## TENANT INSTRUCTIONS

**You may need to:**

[ ] No action required
[ ] Be present during entry
[ ] Secure or confine pets
[ ] Clear access to: _________________________________
[ ] Prepare for treatment by: _________________________________
[ ] Other: _________________________________

---

## YOUR RIGHTS

- You have received at least 24 hours' advance notice as required by law
- Entry will occur during reasonable hours unless otherwise agreed
- Your property will be respected during entry
- You may contact us to reschedule if the time is inconvenient

---

## ALTERNATIVE TIME

If the scheduled time does not work for you, please contact us at least **[24 hours]** before the scheduled entry to arrange an alternative time:

**Phone:** {{manager_phone}}
**Email:** {{manager_email}}

---

## LEGAL BASIS

This notice is provided in accordance with State law and your lease agreement, which permits entry for the purposes stated above with reasonable advance notice.

---

**LANDLORD/PROPERTY MANAGER:**

[SIGNATURE:Landlord]

{{landlord_name}}

---

*Generated by PropManager on {{current_date}}*
"""


# =============================================================================
# CHECKLISTS AND RECEIPTS
# =============================================================================

MOVE_IN_OUT_CHECKLIST = """# MOVE-IN / MOVE-OUT INSPECTION CHECKLIST

**Property Address:** {{property_address}}
**Unit:** {{unit_number}}
**Tenant:** {{tenant_name}}

---

## INSPECTION DETAILS

| | Move-In | Move-Out |
|---|---------|----------|
| **Date** | _____________ | _____________ |
| **Time** | _____________ | _____________ |
| **Inspector** | _____________ | _____________ |

---

## RATING KEY

**Condition Ratings:**
- **E** = Excellent
- **G** = Good
- **F** = Fair
- **P** = Poor
- **N/A** = Not Applicable

---

## LIVING ROOM

| Item | Move-In | Move-Out | Notes |
|------|---------|----------|-------|
| Walls/Paint | _____ | _____ | _________________ |
| Ceiling | _____ | _____ | _________________ |
| Flooring | _____ | _____ | _________________ |
| Windows | _____ | _____ | _________________ |
| Window Coverings | _____ | _____ | _________________ |
| Light Fixtures | _____ | _____ | _________________ |
| Electrical Outlets | _____ | _____ | _________________ |
| Light Switches | _____ | _____ | _________________ |
| Doors | _____ | _____ | _________________ |
| Closets | _____ | _____ | _________________ |

---

## KITCHEN

| Item | Move-In | Move-Out | Notes |
|------|---------|----------|-------|
| Walls/Paint | _____ | _____ | _________________ |
| Ceiling | _____ | _____ | _________________ |
| Flooring | _____ | _____ | _________________ |
| Cabinets | _____ | _____ | _________________ |
| Countertops | _____ | _____ | _________________ |
| Sink | _____ | _____ | _________________ |
| Faucet | _____ | _____ | _________________ |
| Refrigerator | _____ | _____ | _________________ |
| Stove/Oven | _____ | _____ | _________________ |
| Dishwasher | _____ | _____ | _________________ |
| Microwave | _____ | _____ | _________________ |
| Garbage Disposal | _____ | _____ | _________________ |
| Exhaust Fan | _____ | _____ | _________________ |

---

## BEDROOM 1

| Item | Move-In | Move-Out | Notes |
|------|---------|----------|-------|
| Walls/Paint | _____ | _____ | _________________ |
| Ceiling | _____ | _____ | _________________ |
| Flooring | _____ | _____ | _________________ |
| Windows | _____ | _____ | _________________ |
| Window Coverings | _____ | _____ | _________________ |
| Light Fixtures | _____ | _____ | _________________ |
| Closet | _____ | _____ | _________________ |
| Doors | _____ | _____ | _________________ |

---

## BEDROOM 2

| Item | Move-In | Move-Out | Notes |
|------|---------|----------|-------|
| Walls/Paint | _____ | _____ | _________________ |
| Ceiling | _____ | _____ | _________________ |
| Flooring | _____ | _____ | _________________ |
| Windows | _____ | _____ | _________________ |
| Window Coverings | _____ | _____ | _________________ |
| Light Fixtures | _____ | _____ | _________________ |
| Closet | _____ | _____ | _________________ |
| Doors | _____ | _____ | _________________ |

---

## BATHROOM 1

| Item | Move-In | Move-Out | Notes |
|------|---------|----------|-------|
| Walls/Paint | _____ | _____ | _________________ |
| Ceiling | _____ | _____ | _________________ |
| Flooring | _____ | _____ | _________________ |
| Toilet | _____ | _____ | _________________ |
| Sink/Vanity | _____ | _____ | _________________ |
| Faucet | _____ | _____ | _________________ |
| Tub/Shower | _____ | _____ | _________________ |
| Shower Door/Curtain Rod | _____ | _____ | _________________ |
| Mirror/Medicine Cabinet | _____ | _____ | _________________ |
| Exhaust Fan | _____ | _____ | _________________ |
| Towel Bars | _____ | _____ | _________________ |

---

## EXTERIOR/OTHER

| Item | Move-In | Move-Out | Notes |
|------|---------|----------|-------|
| Front Door | _____ | _____ | _________________ |
| Back Door/Patio Door | _____ | _____ | _________________ |
| Balcony/Patio | _____ | _____ | _________________ |
| Garage | _____ | _____ | _________________ |
| Storage | _____ | _____ | _________________ |
| Mailbox | _____ | _____ | _________________ |
| Smoke Detectors | _____ | _____ | _________________ |
| CO Detectors | _____ | _____ | _________________ |
| HVAC Filter | _____ | _____ | _________________ |
| Thermostat | _____ | _____ | _________________ |

---

## KEYS/ACCESS DEVICES

| Item | Move-In Qty | Move-Out Qty | Notes |
|------|-------------|--------------|-------|
| Door Keys | _____ | _____ | _________________ |
| Mailbox Keys | _____ | _____ | _________________ |
| Gate Remote/Card | _____ | _____ | _________________ |
| Garage Remote | _____ | _____ | _________________ |
| Pool Key/Card | _____ | _____ | _________________ |

---

## UTILITY READINGS

| Utility | Move-In Reading | Move-Out Reading |
|---------|-----------------|------------------|
| Electric | _____________ | _____________ |
| Gas | _____________ | _____________ |
| Water | _____________ | _____________ |

---

## ADDITIONAL COMMENTS

**Move-In:**

_________________________________________________________________

_________________________________________________________________

**Move-Out:**

_________________________________________________________________

_________________________________________________________________

---

## MOVE-IN SIGNATURES

By signing below, the parties agree this checklist accurately reflects the condition of the premises at move-in.

**LANDLORD/AGENT:**

[SIGNATURE:Landlord]

Date: _______________

**TENANT:**

[SIGNATURE:Tenant]

Date: _______________

---

## MOVE-OUT SIGNATURES

By signing below, the parties agree this checklist accurately reflects the condition of the premises at move-out.

**LANDLORD/AGENT:**

[SIGNATURE:Landlord]

Date: _______________

**TENANT:**

[SIGNATURE:Tenant]

Date: _______________

---

*Generated by PropManager on {{current_date}}*
"""

SECURITY_DEPOSIT_RECEIPT = """# SECURITY DEPOSIT RECEIPT

**Date:** {{current_date}}

---

## PROPERTY INFORMATION

**Property Address:** {{property_address}}
**Unit:** {{unit_number}}

---

## TENANT INFORMATION

**Tenant Name(s):** {{tenant_name}}

---

## DEPOSIT DETAILS

**Security Deposit Amount:** {{security_deposit}}

**Date Received:** {{current_date}}

**Payment Method:**
[ ] Check #: _____________
[ ] Money Order #: _____________
[ ] Cash
[ ] Electronic Transfer
[ ] Other: _____________

---

## DEPOSIT HOLDING INFORMATION

As required by law, the security deposit is being held at:

**Financial Institution:** _________________________________

**Address:** _________________________________

**Account Type:** [ ] Separate Trust Account [ ] General Account

---

## TERMS AND CONDITIONS

This security deposit is being held in accordance with the terms of the Lease Agreement dated {{lease_start_date}}.

The deposit may be applied to:

1. Unpaid rent or other charges owed under the lease
2. Cleaning costs if the unit is not left in the same condition as at move-in (less normal wear and tear)
3. Repair of damages beyond normal wear and tear
4. Unreturned keys or access devices
5. Other charges as permitted by law and the lease agreement

---

## RETURN OF DEPOSIT

Upon termination of the tenancy and return of the premises:

- The security deposit, less any lawful deductions, will be returned within the time required by state law
- An itemized statement of deductions will be provided if any portion is retained
- The deposit will be mailed to the forwarding address provided by the tenant

---

## ACKNOWLEDGMENT

**Landlord certifies:**
- Receipt of the security deposit in the amount stated above
- The deposit will be held in compliance with applicable laws
- Tenant has been provided with a copy of this receipt

**Tenant acknowledges:**
- Payment of the security deposit in the amount stated above
- Understanding of how the deposit may be used
- Receipt of a copy of this document

---

## SIGNATURES

**LANDLORD/PROPERTY MANAGER:**

[SIGNATURE:Landlord]

Printed Name: {{landlord_name}}

Date: _______________

**TENANT:**

[SIGNATURE:Tenant]

Printed Name: {{tenant_name}}

Date: _______________

---

*This receipt serves as proof of security deposit payment. Tenant should retain a copy for their records.*

*Generated by PropManager on {{current_date}}*
"""


# =============================================================================
# LETTERS
# =============================================================================

TENANT_WELCOME_LETTER = """# WELCOME TO YOUR NEW HOME!

**Date:** {{current_date}}

Dear {{tenant_name}},

Welcome to {{property_address}}, Unit {{unit_number}}! We are delighted to have you as our newest resident.

---

## IMPORTANT CONTACT INFORMATION

**Management Office:**
- Phone: {{manager_phone}}
- Email: {{manager_email}}
- Address: {{office_address}}
- Office Hours: {{office_hours}}

**Emergency Maintenance:**
- After-hours emergency line: _________________________________
- What constitutes an emergency: Water leaks, no heat/AC, security issues, fire

---

## YOUR MOVE-IN CHECKLIST

[ ] Inspect the unit and complete the Move-In Checklist
[ ] Set up utilities in your name (if applicable)
[ ] Obtain renter's insurance
[ ] Update your address with the post office
[ ] Program emergency contacts into your phone
[ ] Locate fire extinguisher and emergency exits
[ ] Test smoke and CO detectors
[ ] Note your parking space number: {{parking_space_numbers}}

---

## RENT INFORMATION

**Monthly Rent:** {{monthly_rent}}
**Due Date:** {{rent_due_day}} of each month
**Grace Period:** {{grace_period_days}} days
**Late Fee:** {{late_fee_amount}}

**Payment Methods:**
- Online Portal: _________________________________
- Mail: {{office_address}}
- In Person: During office hours

---

## IMPORTANT POLICIES

**Maintenance Requests:**
Submit requests through the online portal or contact the office. For emergencies outside office hours, call the emergency maintenance line.

**Guests:**
Extended guests (over 14 days) require management approval.

**Quiet Hours:**
Please be considerate of neighbors, especially between 10 PM and 8 AM.

**Parking:**
Park only in your assigned space. Guest parking is available in designated areas.

**Pets:**
If pets are allowed on your lease, please ensure they are registered and follow all pet policies.

---

## NEARBY AMENITIES

We've compiled some helpful information about the neighborhood:

- Nearest Grocery Store: _________________________________
- Nearest Hospital/Urgent Care: _________________________________
- Public Transportation: _________________________________
- Schools: _________________________________

---

## COMMUNITY AMENITIES

Your community may include:
- Fitness Center
- Pool/Spa
- Clubhouse
- Laundry Facilities
- Package Lockers

*Please see the community rules for hours and guidelines.*

---

## WE'RE HERE TO HELP

Our goal is to make your living experience comfortable and enjoyable. Please don't hesitate to reach out if you have any questions or concerns.

Once again, welcome to your new home!

Warm regards,

**{{landlord_name}}**

{{manager_email}}

{{manager_phone}}

---

*Generated by PropManager on {{current_date}}*
"""

SECURITY_DEPOSIT_RETURN_LETTER = """# SECURITY DEPOSIT RETURN STATEMENT

**Date:** {{current_date}}

**To:** {{tenant_name}}
**Former Address:** {{property_address}}, Unit {{unit_number}}
**Forwarding Address:**

_________________________________

_________________________________

---

## SECURITY DEPOSIT DISPOSITION

This letter provides an itemized statement of your security deposit as required by law.

---

## ORIGINAL DEPOSIT

| Description | Amount |
|-------------|--------|
| Security Deposit Paid | {{security_deposit}} |
| **Total Deposit Held** | **{{security_deposit}}** |

---

## DEDUCTIONS

| Description | Amount |
|-------------|--------|
| Unpaid Rent | $_________ |
| Late Fees | $_________ |
| Cleaning | $_________ |
| Repairs (see itemization below) | $_________ |
| Unreturned Keys | $_________ |
| Other: _________________ | $_________ |
| **Total Deductions** | **$_________** |

---

## ITEMIZED REPAIR/CLEANING COSTS

| Item | Description | Cost |
|------|-------------|------|
| 1 | _________________________________ | $_________ |
| 2 | _________________________________ | $_________ |
| 3 | _________________________________ | $_________ |
| 4 | _________________________________ | $_________ |
| 5 | _________________________________ | $_________ |

*Receipts/invoices for amounts over $_________ are attached.*

---

## DEPOSIT CALCULATION

| | Amount |
|---|--------|
| Original Deposit | {{security_deposit}} |
| Less: Total Deductions | ($________) |
| **Amount Returned to Tenant** | **$_________** |

---

## REFUND METHOD

[ ] Check enclosed (Check #: _________)
[ ] Check mailed separately
[ ] Electronic transfer to account on file
[ ] Amount owed to Landlord: $_________ (Please remit payment within 30 days)

---

## NOTES

_________________________________________________________________

_________________________________________________________________

_________________________________________________________________

---

## QUESTIONS OR DISPUTES

If you have questions about this statement or wish to dispute any deductions, please contact us within 30 days:

**Phone:** {{manager_phone}}
**Email:** {{manager_email}}

---

**LANDLORD/PROPERTY MANAGER:**

[SIGNATURE:Landlord]

{{landlord_name}}

Date: _______________

---

*This statement is provided in compliance with state law regarding security deposit disposition.*

*Generated by PropManager on {{current_date}}*
"""


# =============================================================================
# MIGRATION FUNCTIONS
# =============================================================================

TEMPLATES_TO_CREATE = [
    # Lease Agreements
    {
        "name": "Month-to-Month Rental Agreement",
        "template_type": "lease",
        "description": "A flexible rental agreement with no fixed end date that continues month-to-month until either party provides notice to terminate.",
        "content": MONTH_TO_MONTH_AGREEMENT,
    },
    {
        "name": "Lease Renewal Agreement",
        "template_type": "lease",
        "description": "Agreement to extend an existing lease for a new term with updated rent and conditions.",
        "content": LEASE_RENEWAL_AGREEMENT,
    },
    {
        "name": "Guarantor / Co-Signer Agreement",
        "template_type": "addendum",
        "description": "Agreement where a third party guarantees payment of rent and other lease obligations. Commonly used for students or tenants with limited credit history.",
        "content": GUARANTOR_AGREEMENT,
    },
    {
        "name": "Roommate Agreement",
        "template_type": "addendum",
        "description": "Agreement between roommates outlining rent division, utility sharing, household rules, and responsibilities. Supplements the master lease.",
        "content": ROOMMATE_AGREEMENT,
    },
    # Addendums
    {
        "name": "Pet Addendum",
        "template_type": "pet_agreement",
        "description": "Addendum authorizing pets on the premises with rules, deposits, and liability terms.",
        "content": PET_ADDENDUM,
    },
    {
        "name": "Parking Addendum",
        "template_type": "addendum",
        "description": "Addendum for assigned parking spaces with vehicle registration and parking rules.",
        "content": PARKING_ADDENDUM,
    },
    {
        "name": "Smoke-Free Property Addendum",
        "template_type": "addendum",
        "description": "Addendum establishing smoke-free standards for the property, including prohibited areas and enforcement.",
        "content": NO_SMOKING_ADDENDUM,
    },
    {
        "name": "Smoke and CO Detector Addendum",
        "template_type": "disclosure",
        "description": "Confirms installation and testing of smoke and carbon monoxide detectors with tenant responsibilities for maintenance.",
        "content": SMOKE_CO_DETECTOR_ADDENDUM,
    },
    {
        "name": "Bed Bug Addendum",
        "template_type": "addendum",
        "description": "Disclosure and agreement regarding bed bug prevention, reporting, and treatment responsibilities.",
        "content": BED_BUG_ADDENDUM,
    },
    # Disclosures
    {
        "name": "Lead-Based Paint Disclosure",
        "template_type": "disclosure",
        "description": "Federally required disclosure for housing built before 1978 regarding lead-based paint hazards. Required by Section 1018 of the Residential Lead-Based Paint Hazard Reduction Act.",
        "content": LEAD_PAINT_DISCLOSURE,
    },
    {
        "name": "Mold Information and Disclosure",
        "template_type": "disclosure",
        "description": "Disclosure informing tenants about mold, its health effects, prevention measures, and reporting responsibilities.",
        "content": MOLD_DISCLOSURE,
    },
    # Notices
    {
        "name": "Notice to Vacate",
        "template_type": "notice",
        "description": "Formal notice from tenant to landlord of intent to move out, including forwarding address and move-out procedures.",
        "content": NOTICE_TO_VACATE,
    },
    {
        "name": "Rent Increase Notice",
        "template_type": "notice",
        "description": "Official notice to tenant of an upcoming rent increase with effective date and new amount.",
        "content": RENT_INCREASE_NOTICE,
    },
    {
        "name": "Notice of Entry",
        "template_type": "notice",
        "description": "24-hour advance notice to tenant of landlord's intent to enter the rental unit for inspections, repairs, or showings.",
        "content": NOTICE_OF_ENTRY,
    },
    # Checklists and Receipts
    {
        "name": "Move-In / Move-Out Inspection Checklist",
        "template_type": "other",
        "description": "Comprehensive room-by-room checklist for documenting property condition at move-in and move-out. Includes utility readings and key inventory.",
        "content": MOVE_IN_OUT_CHECKLIST,
    },
    {
        "name": "Security Deposit Receipt",
        "template_type": "other",
        "description": "Receipt acknowledging payment of security deposit with holding information as required by law.",
        "content": SECURITY_DEPOSIT_RECEIPT,
    },
    # Letters
    {
        "name": "Tenant Welcome Letter",
        "template_type": "other",
        "description": "Welcome letter for new tenants with contact information, payment instructions, move-in checklist, and community information.",
        "content": TENANT_WELCOME_LETTER,
    },
    {
        "name": "Security Deposit Return Statement",
        "template_type": "other",
        "description": "Itemized statement of security deposit disposition including deductions and refund amount, as required by law.",
        "content": SECURITY_DEPOSIT_RETURN_LETTER,
    },
]


def create_templates(apps, schema_editor):
    """Create all eDocument templates."""
    EDocumentTemplate = apps.get_model("documents", "EDocumentTemplate")

    for template_data in TEMPLATES_TO_CREATE:
        # Check if template already exists
        if not EDocumentTemplate.objects.filter(name=template_data["name"]).exists():
            EDocumentTemplate.objects.create(
                name=template_data["name"],
                template_type=template_data["template_type"],
                description=template_data["description"],
                content=template_data["content"],
                is_active=True,
            )


def remove_templates(apps, schema_editor):
    """Remove created templates."""
    EDocumentTemplate = apps.get_model("documents", "EDocumentTemplate")

    template_names = [t["name"] for t in TEMPLATES_TO_CREATE]
    EDocumentTemplate.objects.filter(name__in=template_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_seed_lease_template"),
    ]

    operations = [
        migrations.RunPython(create_templates, remove_templates),
    ]
