# Generated by Django 6.0.2 on 2026-02-21 00:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_seed_document_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EDocumentFillableBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant'), ('tenant2', 'Tenant 2'), ('tenant3', 'Tenant 3'), ('tenant4', 'Tenant 4'), ('cosigner', 'Co-Signer')], max_length=20)),
                ('block_order', models.PositiveIntegerField(help_text='Order of appearance in document (parsed from markdown)')),
                ('content', models.TextField(blank=True, default='', help_text='Text content filled in by signer')),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fillable_blocks', to='documents.edocument')),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edocument_fillable_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'eDocument Fillable Block',
                'verbose_name_plural': 'eDocument Fillable Blocks',
                'ordering': ['block_order'],
                'unique_together': {('document', 'block_order')},
            },
        ),
    ]
