# Generated by Django 5.2.11 on 2026-02-19 00:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherMonitorConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('polling_interval_hours', models.PositiveSmallIntegerField(default=2)),
                ('snow_threshold_inches', models.DecimalField(decimal_places=1, default=2.0, max_digits=5)),
                ('wind_threshold_mph', models.DecimalField(decimal_places=1, default=40.0, max_digits=5)),
                ('temp_low_threshold_f', models.DecimalField(decimal_places=1, default=10.0, max_digits=5)),
                ('temp_high_threshold_f', models.DecimalField(decimal_places=1, default=100.0, max_digits=5)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_config', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temperature_f', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feels_like_f', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('humidity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wind_speed_mph', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_gust_mph', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('conditions', models.JSONField(default=dict)),
                ('snow_inches', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rain_inches', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('alert_type', models.CharField(blank=True, choices=[('snow', 'Snow'), ('storm', 'Storm'), ('extreme_heat', 'Extreme Heat'), ('extreme_cold', 'Extreme Cold'), ('wind', 'High Wind'), ('flood', 'Flood')], max_length=15, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='properties.property')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('snow', 'Snow'), ('storm', 'Storm'), ('extreme_heat', 'Extreme Heat'), ('extreme_cold', 'Extreme Cold'), ('wind', 'High Wind'), ('flood', 'Flood')], max_length=15)),
                ('severity', models.CharField(choices=[('watch', 'Watch'), ('warning', 'Warning'), ('emergency', 'Emergency')], default='watch', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('auto_generated', models.BooleanField(default=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_alerts', to='properties.property')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='weather.weathersnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
