# Generated by Django 5.2.11 on 2026-02-19 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherNotificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Descriptive name for this rule (e.g., 'Snow Plowing Reminder')", max_length=200)),
                ('alert_type', models.CharField(choices=[('snow', 'Snow'), ('storm', 'Storm'), ('extreme_heat', 'Extreme Heat'), ('extreme_cold', 'Extreme Cold'), ('wind', 'High Wind'), ('flood', 'Flood')], db_index=True, help_text='The weather condition that triggers this rule.', max_length=15)),
                ('severity', models.CharField(choices=[('all', 'All Severities'), ('watch', 'Watch'), ('warning', 'Warning'), ('emergency', 'Emergency')], default='all', help_text="Minimum severity level to trigger (or 'All' for any).", max_length=10)),
                ('subject_template', models.CharField(help_text='Notification subject. Use {property_name}, {alert_type}, etc.', max_length=255)),
                ('message_template', models.TextField(help_text='Notification body. Available variables: {property_name}, {property_address}, {temperature}, {feels_like}, {humidity}, {wind_speed}, {wind_gust}, {snow_inches}, {rain_inches}, {alert_type}, {severity}, {timestamp}')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('cooldown_hours', models.PositiveSmallIntegerField(default=24, help_text='Hours before this rule can fire again for the same property.')),
                ('property', models.ForeignKey(blank=True, help_text='Leave blank to apply to all properties.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_notification_rules', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherRuleDispatchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rendered_subject', models.CharField(max_length=255)),
                ('rendered_message', models.TextField()),
                ('tenants_notified', models.PositiveIntegerField(default=0)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_dispatches', to='weather.weatheralert')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_rule_dispatches', to='properties.property')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_logs', to='weather.weathernotificationrule')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.weathersnapshot')),
            ],
            options={
                'ordering': ['-dispatched_at'],
                'indexes': [models.Index(fields=['rule', 'property', '-dispatched_at'], name='weather_wea_rule_id_b44ace_idx')],
            },
        ),
    ]
