# Generated by Django 6.0.2 on 2026-02-20 01:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='auto_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='fully_executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='grace_period_days',
            field=models.PositiveSmallIntegerField(default=5, help_text='Days after due date before late fee applies'),
        ),
        migrations.AddField(
            model_name='lease',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lease',
            name='late_fee_type',
            field=models.CharField(choices=[('flat', 'Flat Amount'), ('percent', 'Percentage of Rent'), ('daily', 'Daily Amount')], default='flat', max_length=10),
        ),
        migrations.AddField(
            model_name='lease',
            name='max_occupants',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='lease',
            name='max_pets',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lease',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='move_in_inspection_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='move_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='move_out_inspection_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='parking_space_numbers',
            field=models.CharField(blank=True, default='', help_text='Assigned parking space numbers', max_length=100),
        ),
        migrations.AddField(
            model_name='lease',
            name='parking_spaces',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lease',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='renewal_notice_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Days notice required to not renew'),
        ),
        migrations.AddField(
            model_name='lease',
            name='rent_due_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Day of month rent is due (1-28)'),
        ),
        migrations.AddField(
            model_name='lease',
            name='rent_increase_notice_days',
            field=models.PositiveSmallIntegerField(default=60, help_text='Days notice required for rent increases'),
        ),
        migrations.AddField(
            model_name='lease',
            name='renters_insurance_minimum',
            field=models.DecimalField(decimal_places=2, default=100000, help_text='Minimum liability coverage required', max_digits=10),
        ),
        migrations.AddField(
            model_name='lease',
            name='renters_insurance_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='signature_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='signature_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Signatures'), ('partial', 'Partially Signed'), ('executed', 'Fully Executed')], default='draft', max_length=15),
        ),
        migrations.AddField(
            model_name='lease',
            name='smoking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='subletting_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='utilities_included',
            field=models.JSONField(blank=True, default=list, help_text='List of included utilities, e.g. ["water", "trash", "gas"]'),
        ),
        migrations.CreateModel(
            name='LeaseFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_type', models.CharField(choices=[('application', 'Application Fee'), ('admin', 'Administrative Fee'), ('pet_deposit', 'Pet Deposit'), ('pet_rent', 'Monthly Pet Rent'), ('parking', 'Parking Fee'), ('storage', 'Storage Fee'), ('late', 'Late Payment Fee'), ('nsf', 'NSF/Returned Check Fee'), ('move_in', 'Move-In Fee'), ('move_out', 'Move-Out Fee'), ('cleaning', 'Cleaning Fee'), ('key_replacement', 'Key Replacement'), ('lock_change', 'Lock Change Fee'), ('amenity', 'Amenity Fee'), ('utility', 'Utility Fee'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(help_text='Custom name for this fee', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('one_time', 'One-Time'), ('monthly', 'Monthly'), ('annual', 'Annual'), ('per_occurrence', 'Per Occurrence')], max_length=20)),
                ('is_refundable', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='leases.lease')),
            ],
            options={
                'ordering': ['fee_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeaseOccupant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse/Partner'), ('child', 'Child'), ('roommate', 'Roommate'), ('family', 'Family Member'), ('cosigner', 'Co-Signer'), ('other', 'Other')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_on_lease', models.BooleanField(default=True, help_text='Listed on lease vs. just an occupant')),
                ('is_cosigner', models.BooleanField(default=False)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupants', to='leases.lease')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='LeasePet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('fish', 'Fish'), ('reptile', 'Reptile'), ('small_animal', 'Small Animal'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(blank=True, default='', max_length=100)),
                ('weight_lbs', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('is_service_animal', models.BooleanField(default=False)),
                ('vaccination_current', models.BooleanField(default=False)),
                ('pet_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_pet_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='leases.lease')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaseSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signer_type', models.CharField(choices=[('tenant', 'Tenant'), ('occupant', 'Occupant'), ('cosigner', 'Co-Signer'), ('landlord', 'Landlord/Manager')], max_length=20)),
                ('signer_name', models.CharField(help_text='Typed name confirmation', max_length=200)),
                ('signer_email', models.EmailField(max_length=254)),
                ('signature_image', models.TextField(blank=True, default='', help_text='Base64 encoded signature image')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('signing_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='leases.lease')),
                ('signer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['signer_type', 'signer_name'],
                'unique_together': {('lease', 'signer_email')},
            },
        ),
    ]
