# Generated by Django 6.0.2 on 2026-02-21 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_lease_auto_renewal_lease_fully_executed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='prospective_email',
            field=models.EmailField(blank=True, default='', help_text='Email for prospective tenant (used to send onboarding invitation).', max_length=254),
        ),
        migrations.AddField(
            model_name='lease',
            name='prospective_first_name',
            field=models.CharField(blank=True, default='', help_text='First name of prospective tenant (before onboarding).', max_length=50),
        ),
        migrations.AddField(
            model_name='lease',
            name='prospective_last_name',
            field=models.CharField(blank=True, default='', help_text='Last name of prospective tenant (before onboarding).', max_length=50),
        ),
        migrations.AddField(
            model_name='lease',
            name='prospective_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number of prospective tenant.', max_length=20),
        ),
        migrations.AlterField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Assigned tenant. Leave blank for new tenant onboarding.', limit_choices_to={'role': 'tenant'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leases', to=settings.AUTH_USER_MODEL),
        ),
    ]
