# Generated by Django 5.2.11 on 2026-02-19 05:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0006_payment_reward_applied_and_more'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRewardsConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rewards_enabled', models.BooleanField(default=False, help_text='Master toggle for the rewards program on this property.')),
                ('streak_reward_enabled', models.BooleanField(default=False)),
                ('prepayment_reward_enabled', models.BooleanField(default=False)),
                ('prepayment_threshold_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount of cumulative prepayment needed to earn a reward.', max_digits=10)),
                ('prepayment_reward_amount', models.DecimalField(decimal_places=2, default=0, help_text='Reward amount granted per threshold reached.', max_digits=10)),
                ('auto_apply_rewards', models.BooleanField(default=False, help_text='Automatically apply tenant reward balances to new invoices.')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rewards_config', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Rewards Configuration',
            },
        ),
        migrations.CreateModel(
            name='RewardBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_redeemed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreakRewardTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('months_required', models.PositiveIntegerField(help_text='Consecutive on-time payment months required.')),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_recurring', models.BooleanField(default=False, help_text='If True, re-grants every N months. If False, one-time only.')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_tiers', to='rewards.propertyrewardsconfig')),
            ],
            options={
                'ordering': ['months_required'],
                'unique_together': {('config', 'months_required')},
            },
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('streak_earned', 'Streak Earned'), ('prepayment_earned', 'Prepayment Earned'), ('manual_grant', 'Manual Grant'), ('redeemed', 'Redeemed'), ('reversed', 'Reversed'), ('admin_adjustment', 'Admin Adjustment'), ('expired', 'Expired')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_transactions', to='billing.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_transactions', to='billing.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward_transactions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('streak_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_transactions', to='rewards.streakrewardtier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrepaymentRewardTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cumulative_prepayment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rewards_granted_count', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepayment_reward_trackers', to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepayment_trackers', to='rewards.propertyrewardsconfig')),
            ],
            options={
                'unique_together': {('tenant', 'config')},
            },
        ),
        migrations.CreateModel(
            name='StreakEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_streak_months', models.PositiveIntegerField(default=0)),
                ('last_evaluated_month', models.DateField(blank=True, help_text='First day of the last month evaluated.', null=True)),
                ('streak_broken_at', models.DateField(blank=True, null=True)),
                ('awarded_tier_ids', models.JSONField(default=list, help_text='List of StreakRewardTier PKs already awarded (for non-recurring tiers).')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_evaluations', to='rewards.propertyrewardsconfig')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant', 'config')},
            },
        ),
    ]
