# Generated by Django 6.0.2 on 2026-02-21 01:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name for this provider configuration', max_length=100)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('google_gemini', 'Google Gemini'), ('localai', 'LocalAI')], help_text='AI provider type', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Whether this provider is available for use')),
                ('is_default', models.BooleanField(default=False, help_text='Use as the default provider for AI requests')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Provider-specific configuration (api_key, model, base_url)')),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Providers',
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AICapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.CharField(choices=[('messaging', 'AI Response Messages'), ('workorders', 'AI Work Order Handling'), ('agents', 'AI Agents')], help_text='Type of AI capability', max_length=30, unique=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether this capability is enabled')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Capability-specific configuration')),
                ('provider', models.ForeignKey(blank=True, help_text='Provider to use for this capability', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capabilities', to='ai.aiprovider')),
            ],
            options={
                'verbose_name': 'AI Capability',
                'verbose_name_plural': 'AI Capabilities',
                'ordering': ['capability'],
            },
        ),
    ]
