# Generated by Django 5.2.11 on 2026-02-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcontact',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='groupcontact',
            name='webhook_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='groupcontact',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both'), ('webhook', 'Webhook')], default='email', max_length=7),
        ),
    ]
