# Generated by Django 5.2.11 on 2026-02-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_groupcontact_service_name_groupcontact_webhook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtypesubscription',
            name='event_type',
            field=models.CharField(choices=[('new_work_order', 'New Work Order'), ('payment_received', 'Payment Received'), ('new_message', 'New Message'), ('new_document', 'New Document'), ('lease_expiring', 'Lease Expiring'), ('invoice_overdue', 'Invoice Overdue'), ('weather_alert', 'Weather Alert'), ('new_tenant', 'New Tenant'), ('reward_earned', 'Reward Earned')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tenantnotificationpreference',
            name='category',
            field=models.CharField(choices=[('weather_updates', 'Weather Updates'), ('new_invoice', 'New Invoice'), ('past_due_balance', 'Past Due Balance'), ('messages', 'Messages'), ('announcements', 'Announcements'), ('rewards', 'Rewards')], max_length=20),
        ),
    ]
