# Generated by Django 5.2.11 on 2026-02-19 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_eventtypesubscription_event_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=5)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=6)),
                ('recipient', models.CharField(help_text='Email address or phone number', max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('body_preview', models.TextField(blank=True, default='', help_text='First 500 chars of the message body')),
                ('error_message', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', help_text='Where the dispatch originated: notification, reminder, otp, campaign, etc.', max_length=30)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(default='SMTP Email', max_length=100)),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', help_text='Django email backend class path', max_length=200)),
                ('email_host', models.CharField(help_text='SMTP server hostname', max_length=255)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_use_ssl', models.BooleanField(default=False)),
                ('email_host_user', models.CharField(blank=True, default='', max_length=255)),
                ('email_host_password', models.CharField(blank=True, default='', max_length=255)),
                ('default_from_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_success', models.BooleanField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(default='Twilio SMS', max_length=100)),
                ('provider', models.CharField(choices=[('twilio', 'Twilio')], default='twilio', max_length=20)),
                ('account_sid', models.CharField(max_length=100)),
                ('auth_token', models.CharField(max_length=100)),
                ('phone_number', models.CharField(help_text='Twilio phone number in E.164 format (e.g., +15551234567)', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_success', models.BooleanField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Configuration',
                'ordering': ['-created_at'],
            },
        ),
    ]
